apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-postgres-pvc
  namespace: patient-data-services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
