apiVersion: v1
kind: Service
metadata:
  name: app-postgres
  namespace: patient-data-services
  labels:
    app: app-postgres
spec:
  type: ClusterIP
  selector:
    app: app-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
